export const robots = [
  {
    id: 1,
    name: 'Legion',
    username: '123e4567-e89b',
    email: '123e4567@geth-r.us',
  },
  {
    id: 2,
    name: 'C-3PO',
    username: 'Antonette',
    email: 'peeo@consular.org',
  },
  {
    id: 3,
    name: 'Liberty Prime',
    username: 'Democracy_Non_Negotiable',
    email: 'lib_prime@army.mil',
  },
  {
    id: 4,
    name: 'Bender',
    username: 'Karianne',
    email: '2716057@industrial.bot',
  },
  {
    id: 5,
    name: 'Data',
    username: 'Lore',
    email: 'lore@fleet.fed',
  },
  {
    id: 6,
    name: 'GLaDOS',
    username: 'Samantha',
    email: 'os@aperture.sci',
  },
  {
    id: 7,
    name: 'Centurion',
    username: 'Elwyn.Skiles',
    email: 'cent_e89b@cylon.net',
  },
  {
    id: 8,
    name: 'Servitor',
    username: 'Maxime_Nienow',
    email: '01@mechanicus.me',
  },
  {
    id: 9,
    name: 'HAL 9000',
    username: 'Delphine',
    email: 'hal@dana.ai',
  },
  {
    id: 10,
    name: 'HK-47',
    username: 'hunter-killer',
    email: 'hk-47@assassin.io',
  },
  {
    id: 11,
    name: 'EDI',
    username: 'Enhanced.Defense.Intelligence',
    email: 'edi@cerberus.biz',
  },
  {
    id: 12,
    name: 'Cyberking',
    username: 'Cyberking',
    email: 'king@cybermen.org',
  },
  {
    id: 13,
    name: 'Adjutant',
    username: 'terran.adjutant',
    email: 'adjutant@terran-confederacy.gov',
  },
  {
    id: 14,
    name: 'Nordom',
    username: 'Moriah.Stanton',
    email: 'Nordom@modron.mech',
  },
  {
    id: 15,
    name: 'Dalek Supreme',
    username: 'Moriah.Stanton',
    email: 'supreme@skaro.com',
  },
];
